package com.wyd.mypurse.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import java.math.BigDecimal

/**
 * 预算实体。按月独立存储，通过 year+month 复合主键唯一标识。
 */
@Entity(
    tableName = "budget",
    primaryKeys = ["year", "month"]
)
data class BudgetEntity(
    val year: Int,
    val month: Int,

    /** 月度总预算，null 表示该月无预算 */
    @ColumnInfo(name = "total_budget")
    val totalBudget: BigDecimal? = null,

    /** 是否由系统自动沿用生成 */
    @ColumnInfo(name = "is_auto_generated")
    val isAutoGenerated: Boolean = false,

    /** 创建时间（毫秒时间戳） */
    @ColumnInfo(name = "create_time")
    val createTime: Long = System.currentTimeMillis(),

    /** 最后修改时间（毫秒时间戳） */
    @ColumnInfo(name = "update_time")
    val updateTime: Long = System.currentTimeMillis()
)
